### ISSUE TITLE
filter() function has been inverted in `watch` package

### ISSUE THREAD

**Issue by jcberquist** [davidmurdoch/shopify-theme-sync#14]
It looks to me like when the `watch` package was updated from `0.5.1` to `0.11.0` it resulted in an inverted `filter()` function (see https://github.com/mikeal/watch/commit/e31e72736a764a5c348b0ffc5d44c2bbc449f875)

This means that the current `filter()` function in `app.js` returns false when the `watch` library expects it to return true.

**Comment by davidmurdoch** [comment]
Looks like changing it to:
````
function filter( f, stat, arr ) {
	return (arr || blacklist).indexOf( path.basename( f ).toLowerCase() ) === -1;
}
````

Should fix the walk issue.

And then i'll just need to update any other calls to `filter` to flip flop the bool, i.e., `if ( filter() )` becomes `if( !filter() )`.

Does that sound right to you?

**Comment by jcberquist** [comment]
Yep, that's what I did and it works for me now. Thanks for making this package, it is really convenient to be able to edit theme files locally.

**Comment by maxshelley** [comment]
Just bumped into this and spent a while finding that filter logic reversal. Came here to report it and found the issue. Lesson learned: check the repo first!

No tests in the repo, but @davidmurdoch's change worked for me so I just turned it into a PR, let me know if it doesn't work for you, or if there's any issues. Thanks :smile:
