### ISSUE TITLE
Status Code:404 & Status Code:401

### ISSUE THREAD

**Issue by ElmerZ** [davidmurdoch/shopify-theme-sync#16]
Hi there David, when i saw this post i thought, he is the man hahaha! but now i'm trying to get this work and i'm getting those errors:

Failed: C:\Websites\name-of-page\name-of-page\assets\styles.css.liquid modified

StatusCode: 404
Failed: C:\Websites\name-of-page\name-of-page\assets\styles.css.liquid modified

StatusCode: 401

why i'm getting those erros? i hope you can help me, this is a wonderful tool and i'm very interested on working with this.

**Comment by davidmurdoch** [comment]
Have you edited the config.json to include your _private app_ credentials? You'll should be able to find them by visiting https://{yourshop}.myshopify.com/admin/apps/private

**Comment by ElmerZ** [comment]
Yeap, I edited this way: 
{
    "shops": [
        {
            "name": "alias-shopname",
            "apiKey": "9999998733....the apikey from my shopify",
            "password": "2u2837....password from my shopify",
            "directory": "C:\Websites\alias-shopname",
            "options": {
        "interval": 250,
        "ignoreDotFiles": false,
        "uploadOriginal": false,
        "compress": {
            "js": true
        }
    }
        }
    ]   

## }

Inside the folder alias-shopname, i paste the folder project, with the assets, templates and everything else, but, when i edit something, give me those errors, just now the 401 is not longer in the console, just the 404! thanks for the answer, i hope we can solve this.

**Comment by davidmurdoch** [comment]
Do you have a directory structure like "C:\websites/alias-shopname\3981452". You need numbers there; in your example you just put alias-shopname (your shopname won't work). The template ID is required by Shopify.

Download and extract the zip file of your template from Shopify. **Each template for your shop *must be named after its template ID, e.g., 3981452 and 4870543.***

**Comment by ElmerZ** [comment]
Oh i see, that was my mistake, i suppose that is because my theme, that is online now, is not showing no ID, but if i duplicate and edit that one, then there is a ID! Now is working, thank you so much for your time and your help!

**Comment by ElmerZ** [comment]
Another quickly question, Right now the API is minifying javascript, Css and html (with liquid) ?

**Comment by davidmurdoch** [comment]
Only files that end with .js and .css in the assets folder.
